### ISSUE TITLE
Iterator roadmap

### ISSUE THREAD

**Issue by piever** [JuliaComputing/IndexedTables.jl#151]
List of things to do concerning the transition to a more `Iterator` based style.

Getting rid of inference:

- [ ] port `join` to `collect_columns`

- [ ]  port `broadcast` to `collect_columns`

- [ ] remove other uses of `_promote_op` that I'm missing

Iterator compatibility / better composability:

- [ ] Add method `ndsparse(x)` where `x` is an iterator that iterates pairs

- [ ] Adapt `flatten` to also work when fed an iterator (so that when calling `groupby` with `flatten=true` we can skip one `collect_columns` step

- [ ] Add option `lazy=true` to `groupby`, `groupreduce`, etc... to return the iterator rather than the collected version

- [ ] See which functions can take an iterator as input. Decide what to do for those that cannot (for example `groupby` can't really be done on an iterator as we need the result of `sortperm`, but we could maybe add a trait to iterators to see if `sortperm` is known somehow, some sort of `HasSortPerm()`)

A concern is type piracy. For example, I would like to filter lazily and `reduce` in one go, but we can't add a `reduce` method for a general iterator as that's type piracy, so maybe we should define our own `AbstractRowIterator` for dispatch purposes. Then all lazy algorithms would return a subtype of `AbstractRowIterator`. Then maybe `RowIterator(t, select)` would iterate on `Rows(t, select)`.

We also need to think hard as to what this would mean for the distributed case. I don't have a strong intuition about that.
